version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run: ./build.sh
      - run: ./publish.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master